import { TrafficLight, TrafficCamera, SystemStatusItem } from "./types";

// Mock data for the traffic management system

// Traffic metrics over time
export const trafficVolumeData = [
  { name: "00:00", value: 150, average: 180 },
  { name: "01:00", value: 120, average: 140 },
  { name: "02:00", value: 90, average: 110 },
  { name: "03:00", value: 70, average: 80 },
  { name: "04:00", value: 110, average: 100 },
  { name: "05:00", value: 180, average: 170 },
  { name: "06:00", value: 320, average: 300 },
  { name: "07:00", value: 580, average: 500 },
  { name: "08:00", value: 620, average: 580 },
  { name: "09:00", value: 500, average: 550 },
  { name: "10:00", value: 470, average: 480 },
  { name: "11:00", value: 450, average: 460 },
  { name: "12:00", value: 480, average: 470 },
  { name: "13:00", value: 510, average: 490 },
  { name: "14:00", value: 490, average: 500 },
  { name: "15:00", value: 520, average: 510 },
  { name: "16:00", value: 570, average: 550 },
  { name: "17:00", value: 610, average: 590 },
  { name: "18:00", value: 590, average: 580 },
  { name: "19:00", value: 480, average: 500 },
  { name: "20:00", value: 410, average: 400 },
  { name: "21:00", value: 350, average: 360 },
  { name: "22:00", value: 280, average: 270 },
  { name: "23:00", value: 210, average: 220 },
];

export const congestionData = [
  { name: "Meskel Square", value: 85 },
  { name: "Bole Road", value: 65 },
  { name: "Churchill Ave", value: 45 },
  { name: "Mexico Square", value: 30 },
  { name: "Piassa", value: 75 },
  { name: "Kazanchis", value: 60 },
  { name: "CMC Area", value: 55 },
  { name: "Gotera", value: 70 },
];

export const trafficCameraData = [
  {
    id: "cam-001",
    title: "Meskel Square",
    location: "Addis Ababa, Ethiopia",
    status: "active" as const,
    imgUrl: "/images/meskel-square.png",
    vehicleCount: 45,
    congestionLevel: "high" as const,
  },
  {
    id: "cam-002",
    title: "Bole Road",
    location: "Bole, Addis Ababa",
    status: "active" as const,
    imgUrl: "/images/bole-road.png",
    vehicleCount: 32,
    congestionLevel: "medium" as const,
  },
  {
    id: "cam-003",
    title: "Churchill Avenue",
    location: "Addis Ababa",
    status: "warning" as const,
    imgUrl: "https://images.unsplash.com/photo-1472396961693-142e6e269027?w=800",
    vehicleCount: 18,
    congestionLevel: "low" as const,
  },
  {
    id: "cam-004",
    title: "Mexico Square",
    location: "Addis Ababa",
    status: "active" as const,
    imgUrl: "https://images.unsplash.com/photo-1569336415962-a4bd9f69cd83?w=800",
    vehicleCount: 28,
    congestionLevel: "medium" as const,
  },
  {
    id: "cam-005",
    title: "Piassa Junction",
    location: "Central Addis Ababa",
    status: "active" as const,
    imgUrl: "/images/piassa-junction.png",
    vehicleCount: 52,
    congestionLevel: "high" as const,
  },
  {
    id: "cam-006",
    title: "Gotera Roundabout",
    location: "Gotera, Addis Ababa",
    status: "warning" as const,
    imgUrl: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800",
    vehicleCount: 38,
    congestionLevel: "medium" as const,
  },
  {
    id: "cam-007",
    title: "CMC Intersection",
    location: "CMC, Addis Ababa",
    status: "active" as const,
    imgUrl: "/images/cmc.png",
    vehicleCount: 22,
    congestionLevel: "low" as const,
  },
  {
    id: "cam-008",
    title: "Unity Park Entrance",
    location: "Addis Ababa",
    status: "error" as const,
    imgUrl: "/images/unity-park.png",
  },
];

export const trafficLightData = [
  {
    id: "tl-001",
    name: "Meskel Square & Bole",
    location: "Addis Ababa",
    mode: "auto" as const,
    status: "online" as const,
    currentLight: "red" as const,
    timeLeft: 20,
  },
  {
    id: "tl-002",
    name: "Churchill & Mexico",
    location: "City Center",
    mode: "manual" as const,
    status: "online" as const,
    currentLight: "green" as const,
  },
  {
    id: "tl-003",
    name: "Bole Road Exit",
    location: "Bole",
    mode: "emergency" as const,
    status: "online" as const,
    currentLight: "red" as const,
  },
  {
    id: "tl-004",
    name: "Gotera Roundabout",
    location: "Gotera",
    mode: "auto" as const,
    status: "maintenance" as const,
    currentLight: "red" as const,
  },
  {
    id: "tl-005",
    name: "Piassa Main",
    location: "Piassa",
    mode: "auto" as const,
    status: "online" as const,
    currentLight: "green" as const,
    timeLeft: 15,
  },
  {
    id: "tl-006",
    name: "CMC Junction",
    location: "CMC",
    mode: "auto" as const,
    status: "online" as const,
    currentLight: "yellow" as const,
    timeLeft: 5,
  },
];

export const systemStatusData: SystemStatusItem[] = [
  {
    name: "Edge Computing Server",
    status: "operational",
    uptime: "98.5%",
    load: 42,
  },
  {
    name: "Camera Network",
    status: "operational",
    uptime: "99.2%",
    load: 67,
  },
  {
    name: "Traffic Signals",
    status: "degraded",
    uptime: "95.8%",
    load: 78,
  },
  {
    name: "Analytics Engine",
    status: "operational",
    uptime: "99.9%",
    load: 35,
  },
  {
    name: "IoT Gateway",
    status: "outage",
    uptime: "89.6%",
    load: 0,
  },
];
